import crypto from 'node:crypto';
import { BuyerBusinessModelEngine,buildBuyerBusinessModelFacts,BUYER_BUSINESS_MODEL_VERSION } from './buyerBusinessModel.js';
import { CategoryProcurementMatchEngine,buildCategoryProcurementDimensions,CATEGORY_PROCUREMENT_MATCH_VERSION } from './categoryProcurementMatch.js';
import { CatalogSnapshotService } from './catalogSnapshot.js';
import { calculateProductOpportunity,publicProductOpportunityProjection,PRODUCT_OPPORTUNITY_VERSION } from './productOpportunity.js';
import { CooperationFeasibilityV3Engine,COOPERATION_V3_VERSION } from './cooperationV3.js';
export { buildCategoryBuyerDiscoveryQueries } from './CategoryEvidenceService.js';

const upper=value=>String(value||'').trim().toUpperCase();
const unique=values=>[...new Set((values||[]).filter(Boolean))];
const sha=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const dimensionNames={target_category_procurement_evidence:'TARGET_CATEGORY_PROCUREMENT_EVIDENCE',buyer_business_model_fit:'BUYER_BUSINESS_MODEL_FIT',assortment_depth:'ASSORTMENT_DEPTH',external_sourcing_import:'EXTERNAL_SOURCING_IMPORT',recent_category_activity:'RECENT_CATEGORY_ACTIVITY'};

export function buildCategoryProcurementWorkItems({company_ids=[],product_profiles=['WOMENSWEAR','GENERAL_MERCHANDISE'],job_id=null,research_job_id=null}={}){
  const effectiveJobId=research_job_id||job_id;const rows=[];const seen=new Set();for(const companyId of unique(company_ids.map(String)))for(const productProfile of unique(product_profiles.map(upper))){if(!['WOMENSWEAR','GENERAL_MERCHANDISE'].includes(productProfile))continue;const work_key=`${companyId}:${productProfile}`;if(seen.has(work_key))continue;seen.add(work_key);rows.push({job_id:effectiveJobId,research_job_id:effectiveJobId,company_id:companyId,product_profile:productProfile,work_key});}return rows;
}

export function publicCategoryProcurementProjection(result={}){
  return {category_procurement_match_result_id:result.id||result.category_procurement_match_result_id||null,product_profile:result.product_profile,
    category_procurement_match_score:result.score??null,category_procurement_match_band:result.band||'UNKNOWN',category_procurement_match_status:result.match_status||'NEEDS_PRODUCT_EVIDENCE',
    category_procurement_coverage:Number(result.coverage_percent||0),buyer_business_model:result.buyer_model||'UNKNOWN',buyer_subtype:result.buyer_subtype||'OTHER',
    observed_categories:result.observed_categories||[],reason_codes:result.reason_codes||[],missing_evidence:result.missing_evidence||[],
    dimensions:result.dimensions||[],product_opportunity:result.product_opportunity?publicProductOpportunityProjection(result.product_opportunity):null,
    supplier_access_score:result.supplier_access_score??null,supplier_access_band:result.supplier_access_band||'UNKNOWN',supplier_access_coverage:Number(result.supplier_access_coverage||0),
    product_access_matrix:result.product_access_matrix||'UNKNOWN_PRODUCT',readiness:result.opportunity_readiness||'NEEDS_PRODUCT_EVIDENCE',readiness_blockers:result.readiness_blockers||[],created_at:result.created_at||null};
}

function accessDimensions(previous={}){const breakdown=previous.dimension_breakdown||{};return Object.fromEntries(['external_supplier_openness','supplier_onboarding_accessibility','buying_procurement_accessibility','commercial_operational_feasibility','supplier_lock_in_barrier'].map(key=>[key,breakdown[key]||{state:'UNKNOWN',points:null,evidence_ids:[]} ]));}

export class CategoryProcurementService{
  constructor({pool,buyerEngine=new BuyerBusinessModelEngine(),matchEngine=new CategoryProcurementMatchEngine(),cooperationEngine=new CooperationFeasibilityV3Engine(),catalogService=null}={}){
    if(!pool)throw new Error('CategoryProcurementService requires a PostgreSQL pool');this.pool=pool;this.buyerEngine=buyerEngine;this.matchEngine=matchEngine;this.cooperationEngine=cooperationEngine;this.catalogService=catalogService||new CatalogSnapshotService({pool});
  }
  async loadObservations(companyId){const result=await this.pool.query(`SELECT o.*,s.source_url,s.content_fetched,s.fetch_status,s.page_title FROM leadgen.prospect_category_observations o JOIN leadgen.prospect_category_sources s ON s.id=o.source_id WHERE o.company_id=$1 ORDER BY o.captured_at DESC,o.id`,[companyId]);return result.rows;}
  async loadProducts(profile){const result=await this.pool.query(`SELECT pm.id product_master_id,
    coalesce(rev.product_profile,pm.product_profile) product_profile,
    a.normalized_category,a.normalized_subcategory,a.assignment_status,
    CASE WHEN rev.catalog_status='INACTIVE' THEN 'EXCLUDED' ELSE a.catalog_status END catalog_status,
    a.input_digest
    FROM leadgen.product_master pm
    LEFT JOIN leadgen.product_master_current_revisions rev ON rev.product_master_id=pm.id
    JOIN LATERAL(SELECT x.* FROM leadgen.product_master_taxonomy_assignments x WHERE x.product_master_id=pm.id ORDER BY x.created_at DESC,x.id DESC LIMIT 1)a ON true
    WHERE coalesce(rev.product_profile,pm.product_profile)=$1 ORDER BY pm.id`,[upper(profile)]);return result.rows;}
  async loadContext(companyId,profile){const result=await this.pool.query(`SELECT c.id,c.company_name,c.company_type AS organization_type,c.verification_status,c.lifecycle_status,c.explicit_exclusion_reason,
      EXISTS(SELECT 1 FROM leadgen.company_suppressions s WHERE s.company_id=c.id AND s.lifted_at IS NULL)suppressed,
      EXISTS(SELECT 1 FROM leadgen.historical_customer_company_links l JOIN leadgen.historical_customers h ON h.id=l.historical_customer_id WHERE l.company_id=c.id AND l.link_status='CONFIRMED' AND h.customer_role='INTERNAL_EXISTING_CUSTOMER')existing_customer,
      EXISTS(SELECT 1 FROM leadgen.historical_customer_company_links l WHERE l.company_id=c.id AND l.link_status='CONFIRMED')historical_customer,
      EXISTS(SELECT 1 FROM leadgen.decision_makers dm LEFT JOIN leadgen.decision_maker_product_relevance pr ON pr.decision_maker_id=dm.id AND pr.product_profile=$2 WHERE dm.company_id=c.id AND dm.verification_status='VERIFIED' AND dm.lifecycle_status='ACTIVE' AND dm.normalized_role<>'UNKNOWN' AND (pr.relevance IN('HIGH','MEDIUM') OR pr.decision_maker_id IS NULL))has_verified_decision_route,
      EXISTS(SELECT 1 FROM leadgen.decision_maker_contacts dc JOIN leadgen.decision_makers dm ON dm.id=dc.decision_maker_id WHERE dm.company_id=c.id AND dc.verification_status IN('VALID','ACCEPT_ALL','PUBLICLY_OBSERVED','FORMAT_VALID','BUSINESS_WHATSAPP_OBSERVED'))has_usable_contact_route,
      previous.* FROM leadgen.companies c LEFT JOIN LATERAL(SELECT f.id previous_feasibility_result_id,f.cooperation_feasibility_score previous_score,f.feasibility_band previous_band,f.access_opportunity_matrix previous_access_matrix,f.relationship_status,f.management_match,f.mexico_historical_match,f.dpv_score,f.dimension_breakdown,f.reason_codes previous_reason_codes,f.barrier_signals,f.missing_evidence previous_missing_evidence,f.supplier_route_count,f.verified_decision_maker_count,f.usable_contact_route_count,f.evidence_source_count FROM leadgen.cooperation_feasibility_results f WHERE f.company_id=c.id AND f.product_profile=$2 AND f.category_procurement_match_result_id IS NULL ORDER BY f.calculated_at DESC,f.id DESC LIMIT 1)previous ON true WHERE c.id=$1`,[companyId,upper(profile)]);if(!result.rowCount)throw new Error('Company not found');return result.rows[0];}
  async classifyBuyerAndPersist({researchJobId,companyId,productProfile,executionKey}={}){
    const profile=upper(productProfile);const base=executionKey||`category-procurement:${researchJobId}:${companyId}:${profile}`;const key=`${base}:buyer`;const [observations,context]=await Promise.all([this.loadObservations(companyId),this.loadContext(companyId,profile)]);const facts=buildBuyerBusinessModelFacts({observations,product_profile:profile,company:context});const buyer=await this.buyerEngine.evaluate({facts});const client=await this.pool.connect();
    try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[key]);let saved=await client.query('SELECT * FROM leadgen.buyer_business_model_results WHERE company_id=$1 AND execution_key=$2',[companyId,key]);let replay=true;if(!saved.rowCount){saved=await client.query(`INSERT INTO leadgen.buyer_business_model_results(research_job_id,company_id,buyer_model,buyer_subtype,eligibility_status,priority_tier,confidence_band,reason_codes,evidence_count,calculation_version,input_digest,execution_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)RETURNING *`,[researchJobId,companyId,buyer.buyer_model,buyer.buyer_subtype,buyer.eligibility_status,buyer.priority_tier,buyer.confidence_band,buyer.reason_codes,buyer.evidence_count,BUYER_BUSINESS_MODEL_VERSION,buyer.input_digest,key]);replay=false;for(const id of unique(buyer.evidence_ids))await client.query(`INSERT INTO leadgen.buyer_business_model_evidence(buyer_business_model_result_id,company_id,prospect_category_observation_id)VALUES($1,$2,$3)ON CONFLICT DO NOTHING`,[saved.rows[0].id,companyId,id]);}await client.query('COMMIT');return{...saved.rows[0],evidence_ids:buyer.evidence_ids,idempotent_replay:replay};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
  }
  async calculateCategoryMatchAndPersist({researchJobId,companyId,productProfile,executionKey,buyerBusinessModelResultId=null}={}){
    const profile=upper(productProfile);const key=executionKey||`category-procurement:${researchJobId}:${companyId}:${profile}`;const existing=await this.pool.query('SELECT * FROM leadgen.category_procurement_match_results WHERE company_id=$1 AND product_profile=$2 AND execution_key=$3',[companyId,profile,key]);if(existing.rowCount)return{...existing.rows[0],idempotent_replay:true};
    const [snapshot,observations]=await Promise.all([this.catalogService.ensure(profile),this.loadObservations(companyId)]);let buyerResult;if(buyerBusinessModelResultId){buyerResult=await this.pool.query(`SELECT b.*,coalesce(array_agg(e.prospect_category_observation_id)FILTER(WHERE e.prospect_category_observation_id IS NOT NULL),'{}'::uuid[])evidence_ids FROM leadgen.buyer_business_model_results b LEFT JOIN leadgen.buyer_business_model_evidence e ON e.buyer_business_model_result_id=b.id WHERE b.id=$1 AND b.company_id=$2 GROUP BY b.id`,[buyerBusinessModelResultId,companyId]);}else{const buyer=await this.classifyBuyerAndPersist({researchJobId,companyId,productProfile:profile,executionKey:key});buyerResult={rows:[buyer],rowCount:1};}if(!buyerResult.rowCount)throw new Error('Buyer Business Model result not found');const buyer=buyerResult.rows[0];const built=buildCategoryProcurementDimensions({observations,product_profile:profile,buyer_business_model:buyer});const match=await this.matchEngine.evaluate({...built,buyer_model:buyer.buyer_model,catalog_snapshot:snapshot,catalog_eligible_product_count:snapshot.eligible_product_count,catalog_supported:snapshot.eligible_product_count>0});const digest=sha([snapshot.source_digest,buyer.input_digest,observations.map(item=>[item.id,item.evidence_hash,item.verification_status])]);const client=await this.pool.connect();
    try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[key]);let saved=await client.query('SELECT * FROM leadgen.category_procurement_match_results WHERE company_id=$1 AND product_profile=$2 AND execution_key=$3',[companyId,profile,key]);let replay=true;if(!saved.rowCount){saved=await client.query(`INSERT INTO leadgen.category_procurement_match_results(research_job_id,company_id,product_profile,buyer_business_model_result_id,product_profile_catalog_snapshot_id,score,band,match_status,coverage_percent,calculation_version,taxonomy_version,input_digest,execution_key,reason_codes,missing_evidence,observed_categories)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)RETURNING *`,[researchJobId,companyId,profile,buyer.id,snapshot.id,match.score,match.band,match.match_status,match.coverage_percent,CATEGORY_PROCUREMENT_MATCH_VERSION,snapshot.taxonomy_version,digest,key,match.reason_codes,match.missing_evidence,match.observed_categories]);replay=false;for(const[name,item]of Object.entries(match.dimensions)){const dim=await client.query(`INSERT INTO leadgen.category_procurement_match_dimensions(category_procurement_match_result_id,company_id,dimension,state,points,maximum,reason_codes)VALUES($1,$2,$3,$4,$5,$6,$7)RETURNING id`,[saved.rows[0].id,companyId,dimensionNames[name],item.state,item.points,item.maximum,item.reason_codes]);for(const id of unique(item.evidence_ids))await client.query(`INSERT INTO leadgen.category_procurement_match_evidence(category_procurement_match_dimension_id,company_id,prospect_category_observation_id)VALUES($1,$2,$3)ON CONFLICT DO NOTHING`,[dim.rows[0].id,companyId,id]);}}await client.query('COMMIT');return{...saved.rows[0],buyer_business_model_result_id:buyer.id,idempotent_replay:replay};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
  }
  async calculateProductOpportunityAndPersist({researchJobId,companyId,productProfile,executionKey,categoryProcurementMatchResultId}={}){
    const profile=upper(productProfile);const base=executionKey||`category-procurement:${researchJobId}:${companyId}:${profile}`;const key=`${base}:opportunity`;let existing=await this.pool.query('SELECT * FROM leadgen.product_opportunity_results WHERE company_id=$1 AND product_profile=$2 AND execution_key=$3',[companyId,profile,key]);if(existing.rowCount)return{...existing.rows[0],idempotent_replay:true};const matchResult=await this.pool.query(`SELECT r.*,s.unknown_product_count,s.classified_product_count,s.eligible_product_count FROM leadgen.category_procurement_match_results r JOIN leadgen.product_profile_catalog_snapshots s ON s.id=r.product_profile_catalog_snapshot_id WHERE r.id=$1 AND r.company_id=$2 AND r.research_job_id=$3 AND r.product_profile=$4`,[categoryProcurementMatchResultId,companyId,researchJobId,profile]);if(!matchResult.rowCount)throw new Error('Category Procurement Match result not found');const [products,observations]=await Promise.all([this.loadProducts(profile),this.loadObservations(companyId)]);const row=matchResult.rows[0];const opportunity=calculateProductOpportunity({category_procurement_match_result:row,observed_categories:observations.filter(item=>upper(item.normalized_profile)===profile),products,catalog_snapshot:{eligible_product_count:row.eligible_product_count,classified_product_count:row.classified_product_count,unknown_product_count:row.unknown_product_count}});const client=await this.pool.connect();
    try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[key]);existing=await client.query('SELECT * FROM leadgen.product_opportunity_results WHERE company_id=$1 AND product_profile=$2 AND execution_key=$3',[companyId,profile,key]);let replay=true;if(!existing.rowCount){existing=await client.query(`INSERT INTO leadgen.product_opportunity_results(research_job_id,company_id,product_profile,category_procurement_match_result_id,recommendation_status,candidate_count,reason_codes,missing_catalog_evidence,calculation_version,input_digest,execution_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)RETURNING *`,[researchJobId,companyId,profile,row.id,opportunity.recommendation_status,opportunity.candidate_count,opportunity.reason_codes,opportunity.missing_catalog_evidence,PRODUCT_OPPORTUNITY_VERSION,opportunity.input_digest,key]);replay=false;for(const item of opportunity.candidates)await client.query(`INSERT INTO leadgen.product_opportunity_candidates(product_opportunity_result_id,product_master_id,rank,safe_product_name,product_profile,normalized_category,normalized_subcategory,catalog_status,reason_codes)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[existing.rows[0].id,item.product_master_id,item.rank,item.safe_product_name,item.product_profile,item.normalized_category,item.normalized_subcategory,item.catalog_status,item.reason_codes]);}await client.query('COMMIT');return{...existing.rows[0],candidates:opportunity.candidates,idempotent_replay:replay};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
  }
  async calculateCooperationAndPersist({researchJobId,companyId,productProfile,executionKey,categoryProcurementMatchResultId,productOpportunityResultId=null}={}){
    const profile=upper(productProfile);const base=executionKey||`category-procurement:${researchJobId}:${companyId}:${profile}`;const key=`${base}:cooperation`;let existing=await this.pool.query('SELECT * FROM leadgen.cooperation_feasibility_results WHERE company_id=$1 AND product_profile=$2 AND execution_key=$3',[companyId,profile,key]);if(existing.rowCount)return{...existing.rows[0],idempotent_replay:true};
    const [matchResult,context,observationCount]=await Promise.all([this.pool.query(`SELECT r.*,b.buyer_model,b.buyer_subtype FROM leadgen.category_procurement_match_results r JOIN leadgen.buyer_business_model_results b ON b.id=r.buyer_business_model_result_id WHERE r.id=$1 AND r.company_id=$2 AND r.research_job_id=$3 AND r.product_profile=$4`,[categoryProcurementMatchResultId,companyId,researchJobId,profile]),this.loadContext(companyId,profile),this.pool.query('SELECT count(*)::int count FROM leadgen.prospect_category_observations WHERE company_id=$1 AND verification_status IN(\'VERIFIED\',\'REVIEW\')',[companyId])]);if(!matchResult.rowCount)throw new Error('Category Procurement Match result not found');const match=matchResult.rows[0];let opportunity;if(productOpportunityResultId)opportunity=await this.pool.query('SELECT * FROM leadgen.product_opportunity_results WHERE id=$1 AND category_procurement_match_result_id=$2',[productOpportunityResultId,match.id]);else opportunity=await this.pool.query('SELECT * FROM leadgen.product_opportunity_results WHERE category_procurement_match_result_id=$1 ORDER BY created_at DESC,id DESC LIMIT 1',[match.id]);const candidateCount=Number(opportunity.rows[0]?.candidate_count||0);const relationship=context.suppressed?'SUPPRESSED':context.existing_customer?'INTERNAL_EXISTING_CUSTOMER':context.historical_customer?'HISTORICAL_CRM_LEAD':'NEW_PROSPECT';const cooperation=await this.cooperationEngine.evaluate({supplier_access_dimensions:accessDimensions(context),buyer_model:match.buyer_model,category_procurement_match_band:match.band,category_procurement_match_status:match.match_status,category_procurement_match_score:match.score,category_procurement_coverage:match.coverage_percent,relationship_status:relationship,suppressed:context.suppressed,existing_customer:context.existing_customer,company_verified_active:upper(context.verification_status)==='VERIFIED'&&upper(context.lifecycle_status)==='ACTIVE',eligible_target_organization:!context.explicit_exclusion_reason,has_verified_decision_route:context.has_verified_decision_route,has_usable_contact_route:context.has_usable_contact_route,has_traceable_evidence:Number(observationCount.rows[0].count)>0,cooperation_feasibility_band:context.previous_band,product_opportunity_count:candidateCount});const legacyScore=context.previous_score!=null&&Number.isFinite(Number(context.previous_score))?Number(context.previous_score):cooperation.supplier_access_score??0;const legacyBand=['HIGH','MEDIUM','LOW_MEDIUM','LOW'].includes(upper(context.previous_band))?upper(context.previous_band):cooperation.supplier_access_band==='UNKNOWN'?'LOW':cooperation.supplier_access_band;const client=await this.pool.connect();
    try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[key]);existing=await client.query('SELECT * FROM leadgen.cooperation_feasibility_results WHERE company_id=$1 AND product_profile=$2 AND execution_key=$3',[companyId,profile,key]);let replay=true;if(!existing.rowCount){existing=await client.query(`INSERT INTO leadgen.cooperation_feasibility_results(research_job_id,company_id,product_profile,cooperation_feasibility_score,feasibility_band,access_opportunity_matrix,opportunity_readiness,relationship_status,management_match,mexico_historical_match,dpv_score,dimension_breakdown,reason_codes,barrier_signals,missing_evidence,supplier_route_count,verified_decision_maker_count,usable_contact_route_count,evidence_source_count,rule_version,category_procurement_match_result_id,cooperation_calculation_version,supplier_access_score,supplier_access_band,supplier_access_coverage,product_access_matrix,readiness_blockers,execution_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28)RETURNING *`,[researchJobId,companyId,profile,legacyScore,legacyBand,context.previous_access_matrix||'LOW_PRIORITY',cooperation.opportunity_readiness,relationship,context.management_match,context.mexico_historical_match,context.dpv_score,JSON.stringify(cooperation.dimension_breakdown),unique([...(context.previous_reason_codes||[]),'CATEGORY_PROCUREMENT_V3']),context.barrier_signals||[],unique([...(context.previous_missing_evidence||[]),...(cooperation.missing_evidence||[])]),Number(context.supplier_route_count||0),Number(context.verified_decision_maker_count||0),Number(context.usable_contact_route_count||0),Number(observationCount.rows[0].count),COOPERATION_V3_VERSION,match.id,COOPERATION_V3_VERSION,cooperation.supplier_access_score,cooperation.supplier_access_band,cooperation.supplier_access_coverage,cooperation.product_access_matrix,cooperation.readiness_blockers,key]);replay=false;}await client.query('COMMIT');return{...existing.rows[0],idempotent_replay:replay};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
  }
  async calculateAndPersist({researchJobId,companyId,productProfile,executionKey}={}){
    const profile=upper(productProfile);if(!researchJobId||!companyId||!['WOMENSWEAR','GENERAL_MERCHANDISE'].includes(profile))throw new Error('researchJobId, companyId and a supported productProfile are required');
    const [snapshot,observations,products,context]=await Promise.all([this.catalogService.ensure(profile),this.loadObservations(companyId),this.loadProducts(profile),this.loadContext(companyId,profile)]);
    if(!snapshot)throw new Error('Catalog snapshot unavailable');const key=executionKey||`category-procurement:${researchJobId}:${companyId}:${profile}`;
    const buyerFacts=buildBuyerBusinessModelFacts({observations,product_profile:profile,company:context});const buyer=await this.buyerEngine.evaluate({facts:buyerFacts});
    const built=buildCategoryProcurementDimensions({observations,product_profile:profile,buyer_business_model:buyer});const match=await this.matchEngine.evaluate({...built,buyer_model:buyer.buyer_model,buyer_business_model:buyer,catalog_snapshot:snapshot,catalog_eligible_product_count:snapshot.eligible_product_count,catalog_supported:snapshot.eligible_product_count>0});
    const inputDigest=sha([snapshot.source_digest,buyer.input_digest,observations.map(item=>[item.id,item.evidence_hash,item.verification_status])]);
    const client=await this.pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[key]);
      const replay=await client.query(`SELECT r.*,b.buyer_model,b.buyer_subtype,o.id product_opportunity_result_id,o.recommendation_status,o.candidate_count,f.id cooperation_result_id,f.supplier_access_score,f.supplier_access_band,f.supplier_access_coverage,f.product_access_matrix,f.opportunity_readiness,f.readiness_blockers FROM leadgen.category_procurement_match_results r JOIN leadgen.buyer_business_model_results b ON b.id=r.buyer_business_model_result_id LEFT JOIN leadgen.product_opportunity_results o ON o.category_procurement_match_result_id=r.id LEFT JOIN leadgen.cooperation_feasibility_results f ON f.category_procurement_match_result_id=r.id WHERE r.company_id=$1 AND r.product_profile=$2 AND r.execution_key=$3`,[companyId,profile,key]);
      if(replay.rowCount){await client.query('COMMIT');return {...publicCategoryProcurementProjection(replay.rows[0]),buyer_business_model_result_id:replay.rows[0].buyer_business_model_result_id,product_opportunity_result_id:replay.rows[0].product_opportunity_result_id,cooperation_result_id:replay.rows[0].cooperation_result_id,idempotent_replay:true};}
      const buyerKey=`${key}:buyer`;let buyerSaved=await client.query(`INSERT INTO leadgen.buyer_business_model_results(research_job_id,company_id,buyer_model,buyer_subtype,eligibility_status,priority_tier,confidence_band,reason_codes,evidence_count,calculation_version,input_digest,execution_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(company_id,execution_key) DO NOTHING RETURNING *`,[researchJobId,companyId,buyer.buyer_model,buyer.buyer_subtype,buyer.eligibility_status,buyer.priority_tier,buyer.confidence_band,buyer.reason_codes,buyer.evidence_count,BUYER_BUSINESS_MODEL_VERSION,buyer.input_digest,buyerKey]);if(!buyerSaved.rowCount)buyerSaved=await client.query('SELECT * FROM leadgen.buyer_business_model_results WHERE company_id=$1 AND execution_key=$2',[companyId,buyerKey]);const buyerRow=buyerSaved.rows[0];
      for(const observationId of unique(buyer.evidence_ids))await client.query(`INSERT INTO leadgen.buyer_business_model_evidence(buyer_business_model_result_id,company_id,prospect_category_observation_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[buyerRow.id,companyId,observationId]);
      const matchSaved=await client.query(`INSERT INTO leadgen.category_procurement_match_results(research_job_id,company_id,product_profile,buyer_business_model_result_id,product_profile_catalog_snapshot_id,score,band,match_status,coverage_percent,calculation_version,taxonomy_version,input_digest,execution_key,reason_codes,missing_evidence,observed_categories) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,[researchJobId,companyId,profile,buyerRow.id,snapshot.id,match.score,match.band,match.match_status,match.coverage_percent,CATEGORY_PROCUREMENT_MATCH_VERSION,snapshot.taxonomy_version,inputDigest,key,match.reason_codes,match.missing_evidence,match.observed_categories]);const matchRow=matchSaved.rows[0];
      const dimensionNames={target_category_procurement_evidence:'TARGET_CATEGORY_PROCUREMENT_EVIDENCE',buyer_business_model_fit:'BUYER_BUSINESS_MODEL_FIT',assortment_depth:'ASSORTMENT_DEPTH',external_sourcing_import:'EXTERNAL_SOURCING_IMPORT',recent_category_activity:'RECENT_CATEGORY_ACTIVITY'};
      for(const[name,item]of Object.entries(match.dimensions)){const dim=await client.query(`INSERT INTO leadgen.category_procurement_match_dimensions(category_procurement_match_result_id,company_id,dimension,state,points,maximum,reason_codes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[matchRow.id,companyId,dimensionNames[name],item.state,item.points,item.maximum,item.reason_codes]);for(const observationId of unique(item.evidence_ids))await client.query(`INSERT INTO leadgen.category_procurement_match_evidence(category_procurement_match_dimension_id,company_id,prospect_category_observation_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[dim.rows[0].id,companyId,observationId]);}
      const opportunity=calculateProductOpportunity({category_procurement_match:{...matchRow,catalog_snapshot:snapshot},products,observations:observations.filter(item=>upper(item.normalized_profile)===profile)});const oppKey=`${key}:opportunity`;
      const oppSaved=await client.query(`INSERT INTO leadgen.product_opportunity_results(research_job_id,company_id,product_profile,category_procurement_match_result_id,recommendation_status,candidate_count,reason_codes,missing_catalog_evidence,calculation_version,input_digest,execution_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[researchJobId,companyId,profile,matchRow.id,opportunity.recommendation_status,opportunity.candidate_count,opportunity.reason_codes,opportunity.missing_catalog_evidence,PRODUCT_OPPORTUNITY_VERSION,opportunity.input_digest,oppKey]);
      for(const item of opportunity.candidates)await client.query(`INSERT INTO leadgen.product_opportunity_candidates(product_opportunity_result_id,product_master_id,rank,safe_product_name,product_profile,normalized_category,normalized_subcategory,catalog_status,reason_codes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[oppSaved.rows[0].id,item.product_master_id,item.rank,item.safe_product_name,item.product_profile,item.normalized_category,item.normalized_subcategory,item.catalog_status,item.reason_codes]);
      const relationship=context.suppressed?'SUPPRESSED':context.existing_customer?'INTERNAL_EXISTING_CUSTOMER':context.historical_customer?'HISTORICAL_CRM_LEAD':'NEW_PROSPECT';
      const cooperation=await this.cooperationEngine.evaluate({supplier_access_dimensions:accessDimensions(context),buyer_model:buyer.buyer_model,category_procurement_match_band:match.band,category_procurement_match_status:match.match_status,category_procurement_match_score:match.score,category_procurement_coverage:match.coverage_percent,relationship_status:relationship,suppressed:context.suppressed,existing_customer:context.existing_customer,company_verified_active:upper(context.verification_status)==='VERIFIED'&&upper(context.lifecycle_status)==='ACTIVE',eligible_target_organization:!context.explicit_exclusion_reason,has_verified_decision_route:context.has_verified_decision_route,has_usable_contact_route:context.has_usable_contact_route,has_traceable_evidence:observations.length>0,cooperation_feasibility_band:context.previous_band,product_opportunity_count:opportunity.candidate_count});
      const legacyScore=context.previous_score!=null&&Number.isFinite(Number(context.previous_score))?Number(context.previous_score):cooperation.supplier_access_score??0;const legacyBand=['HIGH','MEDIUM','LOW_MEDIUM','LOW'].includes(upper(context.previous_band))?upper(context.previous_band):cooperation.supplier_access_band==='UNKNOWN'?'LOW':cooperation.supplier_access_band;
      const cooperationSaved=await client.query(`INSERT INTO leadgen.cooperation_feasibility_results(research_job_id,company_id,product_profile,cooperation_feasibility_score,feasibility_band,access_opportunity_matrix,opportunity_readiness,relationship_status,management_match,mexico_historical_match,dpv_score,dimension_breakdown,reason_codes,barrier_signals,missing_evidence,supplier_route_count,verified_decision_maker_count,usable_contact_route_count,evidence_source_count,rule_version,category_procurement_match_result_id,cooperation_calculation_version,supplier_access_score,supplier_access_band,supplier_access_coverage,product_access_matrix,readiness_blockers,execution_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28) RETURNING *`,[researchJobId,companyId,profile,legacyScore,legacyBand,context.previous_access_matrix||'LOW_PRIORITY',cooperation.opportunity_readiness,relationship,context.management_match,context.mexico_historical_match,context.dpv_score,JSON.stringify(cooperation.dimension_breakdown),unique([...(context.previous_reason_codes||[]),...(cooperation.reason_codes||[]),'CATEGORY_PROCUREMENT_V3']),context.barrier_signals||[],unique([...(context.previous_missing_evidence||[]),...(cooperation.missing_evidence||[])]),Number(context.supplier_route_count||0),Number(context.verified_decision_maker_count||0),Number(context.usable_contact_route_count||0),observations.length,COOPERATION_V3_VERSION,matchRow.id,COOPERATION_V3_VERSION,cooperation.supplier_access_score,cooperation.supplier_access_band,cooperation.supplier_access_coverage,cooperation.product_access_matrix,cooperation.readiness_blockers,`${key}:cooperation`]);
      await client.query('COMMIT');return {...publicCategoryProcurementProjection({...matchRow,...buyerRow,...cooperation,product_opportunity:{...oppSaved.rows[0],...opportunity}}),buyer_business_model_result_id:buyerRow.id,product_opportunity_result_id:oppSaved.rows[0].id,cooperation_result_id:cooperationSaved.rows[0].id,idempotent_replay:false};
    }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
  }
  async getCompanyResults(companyId,{resultId=null}={}){const params=[companyId];const clause=resultId?(params.push(resultId),`AND r.id=$${params.length}`):'';const result=await this.pool.query(`SELECT r.*,b.buyer_model,b.buyer_subtype,f.supplier_access_score,f.supplier_access_band,f.supplier_access_coverage,f.product_access_matrix,f.opportunity_readiness,f.readiness_blockers,
      CASE WHEN o.id IS NULL THEN NULL ELSE jsonb_build_object('id',o.id,'product_profile',o.product_profile,'recommendation_status',o.recommendation_status,'candidate_count',o.candidate_count,'reason_codes',o.reason_codes,'missing_catalog_evidence',o.missing_catalog_evidence,'created_at',o.created_at,'candidates',coalesce((SELECT jsonb_agg(jsonb_build_object('product_master_id',c.product_master_id,'rank',c.rank,'safe_product_name',c.safe_product_name,'product_profile',c.product_profile,'normalized_category',c.normalized_category,'normalized_subcategory',c.normalized_subcategory,'catalog_status',c.catalog_status,'reason_codes',c.reason_codes)ORDER BY c.rank)FROM leadgen.product_opportunity_candidates c WHERE c.product_opportunity_result_id=o.id),'[]'::jsonb))END product_opportunity
      FROM leadgen.category_procurement_match_results r JOIN leadgen.buyer_business_model_results b ON b.id=r.buyer_business_model_result_id LEFT JOIN leadgen.product_opportunity_results o ON o.category_procurement_match_result_id=r.id LEFT JOIN leadgen.cooperation_feasibility_results f ON f.category_procurement_match_result_id=r.id WHERE r.company_id=$1 ${clause} ORDER BY r.product_profile,r.created_at DESC,r.id DESC`,params);return result.rows.map(publicCategoryProcurementProjection);}
  dispose(){this.buyerEngine.dispose?.();this.matchEngine.dispose?.();this.cooperationEngine.dispose?.();}
}
